import type React from 'react'
import { createContext, useContext, useState, useEffect } from 'react'

export type Language = 'de' | 'en' | 'es' | 'it' | 'fr'

interface LanguageContextType {
  language: Language
  setLanguage: (lang: Language) => void
  t: (key: string) => string
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

export const useLanguage = () => {
  const context = useContext(LanguageContext)
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider')
  }
  return context
}

interface LanguageProviderProps {
  children: React.ReactNode
}

export const LanguageProvider: React.FC<LanguageProviderProps> = ({ children }) => {
  const [language, setLanguage] = useState<Language>(() => {
    // Get saved language or detect browser language
    const savedLanguage = localStorage.getItem('stake-fabrik-language') as Language
    if (savedLanguage && ['de', 'en', 'es', 'it', 'fr'].includes(savedLanguage)) {
      return savedLanguage
    }

    // Detect browser language
    const browserLang = navigator.language.slice(0, 2) as Language
    if (['de', 'en', 'es', 'it', 'fr'].includes(browserLang)) {
      return browserLang
    }

    return 'de' // Default to German
  })

  useEffect(() => {
    localStorage.setItem('stake-fabrik-language', language)
  }, [language])

  const t = (key: string): string => {
    return translations[language]?.[key] || translations.en[key] || key
  }

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

// Complete translations for all languages
const translations: Record<Language, Record<string, string>> = {
  de: {
    // Header & Navigation
    'nav.staking': 'Staking',
    'nav.governance': 'Governance',
    'nav.analytics': 'Analytics',
    'nav.docs': 'Docs',
    'nav.connect': 'Wallet verbinden',
    'nav.deposit': 'Einzahlen',
    'nav.profile': 'Profil',

    // Hero Section
    'hero.badge': 'Next Generation Staking',
    'hero.title1': 'STAKE',
    'hero.title2': 'FABRIK',
    'hero.subtitle': 'INDUSTRIAL STAKING',
    'hero.description': 'Intelligente Euro-basierte Staking-Pläne auf BNB Smart Chain. Wöchentliche Auszahlungen mit unserer Factory-Level Infrastruktur.',
    'hero.weekly': 'Wöchentlich',
    'hero.your_tvl': 'Dein TVL',
    'hero.smart_chain': 'Smart Chain',
    'hero.cta_stake': 'Jetzt Staken',
    'hero.cta_analytics': 'Analytics',
    'hero.live_dashboard': 'Live Dashboard',
    'hero.total_staked': 'Total Gestaked',
    'hero.rewards': 'Rewards',
    'hero.bnb_chain_token': 'BNB Chain Token',

    // Features Section
    'features.title': 'Warum Stake Fabrik?',
    'features.description': 'Unsere industrielle Infrastruktur bietet höchste Sicherheit, Effizienz und Rentabilität für deine Investitionen.',
    'features.security.title': 'Industrial Security',
    'features.security.description': 'Schlacht-getestete Smart Contracts mit Factory-Grade Sicherheitsprotokollen und Multi-Sig Wallets.',
    'features.automation.title': 'Automated Operations',
    'features.automation.description': 'Vollautomatisierte Staking-Mechanismen mit Compound-Rewards und intelligenter Ertragsoptimierung.',
    'features.scalable.title': 'Scalable Infrastructure',
    'features.scalable.description': 'Multiple Produktionslinien für institutionelle Skalierung mit flexiblen Lock-Perioden.',

    // Staking Plans
    'staking.title': 'BNB Chain Staking Pläne',
    'staking.description': 'Wähle dein bevorzugtes Token und den passenden Plan. Alle Pläne bieten wöchentliche Auszahlungen auf der BNB Smart Chain.',
    'staking.vista_title': 'Vista Finance (VISTA)',
    'staking.mirror_title': '4-Way Mirror Money (4WMM)',
    'staking.geuro_title': 'GEURO (GEURO)',
    'staking.plan_description': 'Wähle zwischen 3 verschiedenen Staking-Stufen mit unterschiedlichen Mindestbeträgen',
    'staking.starter': 'Starter',
    'staking.standard': 'Standard',
    'staking.premium': 'Premium',
    'staking.weekly': 'Wöchentlich',
    'staking.minimum': 'Mindestbetrag',
    'staking.lock_time': 'Lock-Zeit',
    'staking.yearly': 'Jährlich (ca.)',
    'staking.pool_capacity': 'Pool Kapazität',
    'staking.description_250': '250 Euro minimum - 0.5% wöchentliche Rendite',
    'staking.description_500': '500 Euro minimum - 1% wöchentliche Rendite',
    'staking.description_1000': '1000 Euro minimum - 2% wöchentliche Rendite',
    'staking.btn_stake': 'Jetzt Staken',

    // Active Positions
    'positions.title': 'Deine Aktiven Positionen',
    'positions.description': 'Überwache und verwalte deine BNB Chain Staking-Positionen',
    'positions.staked_amount': 'Gestakte Menge',
    'positions.current_rewards': 'Aktuelle Rewards',
    'positions.weeks_active': 'Wochen aktiv',
    'positions.status': 'Status',
    'positions.network': 'Netzwerk',
    'positions.unlocked': 'Entsperrt',
    'positions.locked': 'Gesperrt',
    'positions.btn_rewards': 'Rewards',
    'positions.btn_unstake': 'Unstake',

    // Staking Modals
    'modal.stake_title': 'BNB Chain Staking',
    'modal.weekly_return': 'Wöchentliche Rendite',
    'modal.lock_time': 'Lock-Zeit',
    'modal.one_week': '1 Woche',
    'modal.token': 'Token',
    'modal.network': 'Netzwerk',
    'modal.yearly_approx': 'Jährlich (ca.)',
    'modal.amount_label': 'Euro Betrag zum Staken',
    'modal.amount_placeholder': 'Minimum: {amount} EUR',
    'modal.balance': 'Balance',
    'modal.minimum_note': 'Minimum: €{amount} | Wöchentlich: {rate}% | 1 Woche Lock',
    'modal.connect_wallet': 'Bitte verbinde dein Wallet für BNB Smart Chain',
    'modal.estimated_returns': 'Geschätzte Rendite',
    'modal.weekly': 'Wöchentlich',
    'modal.monthly': 'Monatlich (ca.)',
    'modal.yearly': 'Jährlich (ca.)',
    'modal.btn_cancel': 'Abbrechen',
    'modal.btn_stake': '€{amount} Staken',
    'modal.processing': 'Verarbeitung...',
    'modal.meets_requirements': '✓ Betrag entspricht den Mindestanforderungen',

    // Footer
    'footer.description': 'Industrial-grade decentralized staking infrastructure engineered for maximum efficiency.',
    'footer.protocol': 'Protocol',
    'footer.community': 'Community',
    'footer.resources': 'Resources',
    'footer.documentation': 'Documentation',
    'footer.whitepaper': 'Whitepaper',
    'footer.security': 'Security',
    'footer.bug_bounty': 'Bug Bounty',
    'footer.brand_assets': 'Brand Assets',
    'footer.discord': 'Discord',
    'footer.telegram': 'Telegram',
    'footer.twitter': 'Twitter',
    'footer.github': 'GitHub',
    'footer.copyright': '© 2024 Stake Fabrik. All rights reserved.',

    // Governance
    'governance.badge': 'Decentralized Governance',
    'governance.title1': 'STAKE',
    'governance.title2': 'GOVERNANCE',
    'governance.subtitle': 'INDUSTRIAL DEMOCRACY',
    'governance.description': 'Shape the future of Stake Fabrik through decentralized governance. Vote on proposals, delegate your tokens, and participate in Factory-Level protocol decisions.',
    'governance.voting_power': 'Voting Power',
    'governance.participation': 'Participation',
    'governance.treasury': 'Treasury',
    'governance.btn_create': 'Create Proposal',
    'governance.btn_delegates': 'View Delegates',

    // Analytics
    'analytics.badge': 'Real-time Analytics',
    'analytics.title1': 'STAKE',
    'analytics.title2': 'ANALYTICS',
    'analytics.subtitle': 'INDUSTRIAL METRICS',
    'analytics.description': 'Comprehensive analytics and insights into the Stake Fabrik ecosystem. Track performance, user metrics, and protocol health with Factory-Level precision.',
    'analytics.total_tvl': 'Total TVL',
    'analytics.active_users': 'Active Users',
    'analytics.avg_weekly': 'Avg Weekly',

    // User Profile
    'profile.title': 'USER PROFILE',
    'profile.subtitle': 'Factory Operator Dashboard',
    'profile.wallet_info': 'Wallet Information',
    'profile.address': 'Address',
    'profile.network': 'Network',
    'profile.status': 'Status',
    'profile.connected': 'Connected',
    'profile.available_balance': 'Available Balance',
    'profile.ready_staking': 'Ready for staking',
    'profile.btn_deposit_more': 'Deposit More',
    'profile.btn_view_transactions': 'View Transactions',
    'profile.staking_statistics': 'Staking Statistics',
    'profile.total_staked': 'Total Staked',
    'profile.total_rewards': 'Total Rewards',
    'profile.active_positions': 'Active Positions',
    'profile.avg_weekly_return': 'Avg Weekly Return',
    'profile.account_info': 'Account Information',
    'profile.member_since': 'Member Since',
    'profile.staking_days': 'Staking Days',
    'profile.portfolio_value': 'Total Portfolio Value',
    'profile.operator_level': 'Operator Level',
    'profile.advanced': 'Advanced',
    'profile.btn_settings': 'Account Settings',
    'profile.btn_bscscan': 'View on BSCScan',

    // Deposit Modal
    'deposit.title': 'Crypto Deposit',
    'deposit.description': 'Send crypto to the address below to fund your staking account',
    'deposit.select_crypto': 'Select Cryptocurrency',
    'deposit.min': 'Min',
    'deposit.deposit_address': 'Deposit Address',
    'deposit.network': 'Network',
    'deposit.qr_code': 'QR Code',
    'deposit.btn_show_qr': 'Show QR Code',
    'deposit.important_instructions': 'Important Instructions',
    'deposit.instruction_1': 'Only send {token} to this address on {network}',
    'deposit.instruction_2': 'Minimum deposit: {amount} {token}',
    'deposit.instruction_3': 'Funds will be credited after 3-6 network confirmations',
    'deposit.instruction_4': 'Do not send from exchange accounts that don\'t support smart contracts',
    'deposit.processing_time': 'Processing Time',
    'deposit.processing_typical': 'Typical processing time: 5-15 minutes',
    'deposit.processing_update': 'Your balance will be automatically updated',
    'deposit.processing_notification': 'You\'ll receive a notification when funds arrive',
    'deposit.btn_copy': 'Copy Address',
    'deposit.btn_bscscan': 'View on BSCScan',
    'deposit.recent_deposits': 'Recent Deposits',
    'deposit.confirmed': 'Confirmed',
    'deposit.pending': 'Pending',
    'deposit.address_copied': 'Address copied to clipboard!',

    // Additional translations
    'features.why_title': 'Warum Stake Fabrik?',
    'staking.plans_title': 'BNB Chain Staking Pläne',
    'staking.choose_description': 'Wähle dein bevorzugtes Token und den passenden Plan. Alle Pläne bieten wöchentliche Auszahlungen auf der BNB Smart Chain.',
    'staking.choose_tiers': 'Wähle zwischen 3 verschiedenen Staking-Stufen mit unterschiedlichen Mindestbeträgen',
    'staking.start_now': 'Jetzt Staken',
    'positions.monitor': 'Überwache und verwalte deine BNB Chain Staking-Positionen',
    'modal.weekly_return_label': 'Wöchentliche Rendite',
    'modal.yearly_approx_label': 'Jährlich (ca.)',
    'modal.amount_minimum': 'Minimum: {amount} EUR',
    'modal.estimated_weekly': 'Wöchentlich:',
    'modal.estimated_monthly': 'Monatlich (ca.):',
    'modal.estimated_yearly': 'Jährlich (ca.):',

    // Additional Modal translations
    'modal.btn_stake_amount': '€{amount} Staken',
    'modal.amount_placeholder_de': 'Minimum: {amount} EUR',
    'modal.meets_requirements_de': '✓ Betrag entspricht den Mindestanforderungen',

    // Common
    'common.weeks': 'Wochen',
    'common.days': 'days',
    'common.bnb_chain': 'BNB Chain',
    'common.eur': 'EUR',
    'common.close': 'Close',
    'common.copy': 'Copy',
    'common.loading': 'Loading...',
  },

  en: {
    // Header & Navigation
    'nav.staking': 'Staking',
    'nav.governance': 'Governance',
    'nav.analytics': 'Analytics',
    'nav.docs': 'Docs',
    'nav.connect': 'Connect Wallet',
    'nav.deposit': 'Deposit',
    'nav.profile': 'Profile',

    // Hero Section
    'hero.badge': 'Next Generation Staking',
    'hero.title1': 'STAKE',
    'hero.title2': 'FABRIK',
    'hero.subtitle': 'INDUSTRIAL STAKING',
    'hero.description': 'Smart Euro-based staking plans on BNB Smart Chain. Weekly payouts with our Factory-Level infrastructure.',
    'hero.weekly': 'Weekly',
    'hero.your_tvl': 'Your TVL',
    'hero.smart_chain': 'Smart Chain',
    'hero.cta_stake': 'Start Staking',
    'hero.cta_analytics': 'Analytics',
    'hero.live_dashboard': 'Live Dashboard',
    'hero.total_staked': 'Total Staked',
    'hero.rewards': 'Rewards',
    'hero.bnb_chain_token': 'BNB Chain Token',

    // Features Section
    'features.title': 'Why Stake Fabrik?',
    'features.description': 'Our industrial infrastructure provides highest security, efficiency and profitability for your investments.',
    'features.security.title': 'Industrial Security',
    'features.security.description': 'Battle-tested smart contracts with factory-grade security protocols and multi-sig wallets.',
    'features.automation.title': 'Automated Operations',
    'features.automation.description': 'Fully automated staking mechanisms with compound rewards and intelligent yield optimization.',
    'features.scalable.title': 'Scalable Infrastructure',
    'features.scalable.description': 'Multiple production lines for institutional scaling with flexible lock periods.',

    // Staking Plans
    'staking.title': 'BNB Chain Staking Plans',
    'staking.description': 'Choose your preferred token and matching plan. All plans offer weekly payouts on BNB Smart Chain.',
    'staking.vista_title': 'Vista Finance (VISTA)',
    'staking.mirror_title': '4-Way Mirror Money (4WMM)',
    'staking.geuro_title': 'GEURO (GEURO)',
    'staking.plan_description': 'Choose between 3 different staking tiers with varying minimum amounts',
    'staking.starter': 'Starter',
    'staking.standard': 'Standard',
    'staking.premium': 'Premium',
    'staking.weekly': 'Weekly',
    'staking.minimum': 'Minimum',
    'staking.lock_time': 'Lock Time',
    'staking.yearly': 'Yearly (approx.)',
    'staking.pool_capacity': 'Pool Capacity',
    'staking.description_250': '250 Euro minimum - 0.5% weekly returns',
    'staking.description_500': '500 Euro minimum - 1% weekly returns',
    'staking.description_1000': '1000 Euro minimum - 2% weekly returns',
    'staking.btn_stake': 'Stake Now',

    // Active Positions
    'positions.title': 'Your Active Positions',
    'positions.description': 'Monitor and manage your BNB Chain staking positions',
    'positions.staked_amount': 'Staked Amount',
    'positions.current_rewards': 'Current Rewards',
    'positions.weeks_active': 'Weeks Active',
    'positions.status': 'Status',
    'positions.network': 'Network',
    'positions.unlocked': 'Unlocked',
    'positions.locked': 'Locked',
    'positions.btn_rewards': 'Rewards',
    'positions.btn_unstake': 'Unstake',

    // Staking Modals
    'modal.stake_title': 'BNB Chain Staking',
    'modal.weekly_return': 'Weekly Return',
    'modal.lock_time': 'Lock Time',
    'modal.one_week': '1 Week',
    'modal.token': 'Token',
    'modal.network': 'Network',
    'modal.yearly_approx': 'Yearly (approx.)',
    'modal.amount_label': 'Euro Amount to Stake',
    'modal.amount_placeholder': 'Minimum: {amount} EUR',
    'modal.balance': 'Balance',
    'modal.minimum_note': 'Minimum: €{amount} | Weekly: {rate}% | 1 Week Lock',
    'modal.connect_wallet': 'Please connect your wallet for BNB Smart Chain',
    'modal.estimated_returns': 'Estimated Returns',
    'modal.weekly': 'Weekly',
    'modal.monthly': 'Monthly (approx.)',
    'modal.yearly': 'Yearly (approx.)',
    'modal.btn_cancel': 'Cancel',
    'modal.btn_stake': 'Stake €{amount}',
    'modal.processing': 'Processing...',
    'modal.meets_requirements': '✓ Amount meets minimum requirements',

    // Footer
    'footer.description': 'Industrial-grade decentralized staking infrastructure engineered for maximum efficiency.',
    'footer.protocol': 'Protocol',
    'footer.community': 'Community',
    'footer.resources': 'Resources',
    'footer.documentation': 'Documentation',
    'footer.whitepaper': 'Whitepaper',
    'footer.security': 'Security',
    'footer.bug_bounty': 'Bug Bounty',
    'footer.brand_assets': 'Brand Assets',
    'footer.discord': 'Discord',
    'footer.telegram': 'Telegram',
    'footer.twitter': 'Twitter',
    'footer.github': 'GitHub',
    'footer.copyright': '© 2024 Stake Fabrik. All rights reserved.',

    // Governance
    'governance.badge': 'Decentralized Governance',
    'governance.title1': 'STAKE',
    'governance.title2': 'GOVERNANCE',
    'governance.subtitle': 'INDUSTRIAL DEMOCRACY',
    'governance.description': 'Shape the future of Stake Fabrik through decentralized governance. Vote on proposals, delegate your tokens, and participate in Factory-Level protocol decisions.',
    'governance.voting_power': 'Voting Power',
    'governance.participation': 'Participation',
    'governance.treasury': 'Treasury',
    'governance.btn_create': 'Create Proposal',
    'governance.btn_delegates': 'View Delegates',

    // Analytics
    'analytics.badge': 'Real-time Analytics',
    'analytics.title1': 'STAKE',
    'analytics.title2': 'ANALYTICS',
    'analytics.subtitle': 'INDUSTRIAL METRICS',
    'analytics.description': 'Comprehensive analytics and insights into the Stake Fabrik ecosystem. Track performance, user metrics, and protocol health with Factory-Level precision.',
    'analytics.total_tvl': 'Total TVL',
    'analytics.active_users': 'Active Users',
    'analytics.avg_weekly': 'Avg Weekly',

    // User Profile
    'profile.title': 'USER PROFILE',
    'profile.subtitle': 'Factory Operator Dashboard',
    'profile.wallet_info': 'Wallet Information',
    'profile.address': 'Address',
    'profile.network': 'Network',
    'profile.status': 'Status',
    'profile.connected': 'Connected',
    'profile.available_balance': 'Available Balance',
    'profile.ready_staking': 'Ready for staking',
    'profile.btn_deposit_more': 'Deposit More',
    'profile.btn_view_transactions': 'View Transactions',
    'profile.staking_statistics': 'Staking Statistics',
    'profile.total_staked': 'Total Staked',
    'profile.total_rewards': 'Total Rewards',
    'profile.active_positions': 'Active Positions',
    'profile.avg_weekly_return': 'Avg Weekly Return',
    'profile.account_info': 'Account Information',
    'profile.member_since': 'Member Since',
    'profile.staking_days': 'Staking Days',
    'profile.portfolio_value': 'Total Portfolio Value',
    'profile.operator_level': 'Operator Level',
    'profile.advanced': 'Advanced',
    'profile.btn_settings': 'Account Settings',
    'profile.btn_bscscan': 'View on BSCScan',

    // Deposit Modal
    'deposit.title': 'Crypto Deposit',
    'deposit.description': 'Send crypto to the address below to fund your staking account',
    'deposit.select_crypto': 'Select Cryptocurrency',
    'deposit.min': 'Min',
    'deposit.deposit_address': 'Deposit Address',
    'deposit.network': 'Network',
    'deposit.qr_code': 'QR Code',
    'deposit.btn_show_qr': 'Show QR Code',
    'deposit.important_instructions': 'Important Instructions',
    'deposit.instruction_1': 'Only send {token} to this address on {network}',
    'deposit.instruction_2': 'Minimum deposit: {amount} {token}',
    'deposit.instruction_3': 'Funds will be credited after 3-6 network confirmations',
    'deposit.instruction_4': 'Do not send from exchange accounts that don\'t support smart contracts',
    'deposit.processing_time': 'Processing Time',
    'deposit.processing_typical': 'Typical processing time: 5-15 minutes',
    'deposit.processing_update': 'Your balance will be automatically updated',
    'deposit.processing_notification': 'You\'ll receive a notification when funds arrive',
    'deposit.btn_copy': 'Copy Address',
    'deposit.btn_bscscan': 'View on BSCScan',
    'deposit.recent_deposits': 'Recent Deposits',
    'deposit.confirmed': 'Confirmed',
    'deposit.pending': 'Pending',
    'deposit.address_copied': 'Address copied to clipboard!',

    // Additional translations
    'features.why_title': 'Why Stake Fabrik?',
    'staking.plans_title': 'BNB Chain Staking Plans',
    'staking.choose_description': 'Choose your preferred token and matching plan. All plans offer weekly payouts on BNB Smart Chain.',
    'staking.choose_tiers': 'Choose between 3 different staking tiers with varying minimum amounts',
    'staking.start_now': 'Stake Now',
    'positions.monitor': 'Monitor and manage your BNB Chain staking positions',
    'modal.weekly_return_label': 'Weekly Return',
    'modal.yearly_approx_label': 'Yearly (approx.)',
    'modal.amount_minimum': 'Minimum: {amount} EUR',
    'modal.estimated_weekly': 'Weekly:',
    'modal.estimated_monthly': 'Monthly (approx.):',
    'modal.estimated_yearly': 'Yearly (approx.):',

    // Additional Modal translations
    'modal.btn_stake_amount': 'Stake €{amount}',

    // Common
    'common.weeks': 'weeks',
    'common.days': 'days',
    'common.bnb_chain': 'BNB Chain',
    'common.eur': 'EUR',
    'common.close': 'Close',
    'common.copy': 'Copy',
    'common.loading': 'Loading...',
  },

  es: {
    // Header & Navigation
    'nav.staking': 'Staking',
    'nav.governance': 'Gobernanza',
    'nav.analytics': 'Analíticas',
    'nav.docs': 'Docs',
    'nav.connect': 'Conectar Wallet',
    'nav.deposit': 'Depositar',
    'nav.profile': 'Perfil',

    // Hero Section
    'hero.badge': 'Staking de Nueva Generación',
    'hero.title1': 'STAKE',
    'hero.title2': 'FABRIK',
    'hero.subtitle': 'STAKING INDUSTRIAL',
    'hero.description': 'Planes de staking inteligentes basados en euros en BNB Smart Chain. Pagos semanales con nuestra infraestructura de nivel industrial.',
    'hero.weekly': 'Semanal',
    'hero.your_tvl': 'Tu TVL',
    'hero.smart_chain': 'Smart Chain',
    'hero.cta_stake': 'Comenzar Staking',
    'hero.cta_analytics': 'Analíticas',
    'hero.live_dashboard': 'Panel en Vivo',
    'hero.total_staked': 'Total en Staking',
    'hero.rewards': 'Recompensas',
    'hero.bnb_chain_token': 'Token BNB Chain',

    // Features Section
    'features.title': '¿Por qué Stake Fabrik?',
    'features.description': 'Nuestra infraestructura industrial proporciona la máxima seguridad, eficiencia y rentabilidad para tus inversiones.',
    'features.security.title': 'Seguridad Industrial',
    'features.security.description': 'Contratos inteligentes probados en batalla con protocolos de seguridad de grado industrial y wallets multi-sig.',
    'features.automation.title': 'Operaciones Automatizadas',
    'features.automation.description': 'Mecanismos de staking completamente automatizados con recompensas compuestas y optimización inteligente de rendimiento.',
    'features.scalable.title': 'Infraestructura Escalable',
    'features.scalable.description': 'Múltiples líneas de producción para escalado institucional con períodos de bloqueo flexibles.',

    // Staking Plans
    'staking.title': 'Planes de Staking BNB Chain',
    'staking.description': 'Elige tu token preferido y el plan correspondiente. Todos los planes ofrecen pagos semanales en BNB Smart Chain.',
    'staking.vista_title': 'Vista Finance (VISTA)',
    'staking.mirror_title': '4-Way Mirror Money (4WMM)',
    'staking.geuro_title': 'GEURO (GEURO)',
    'staking.plan_description': 'Elige entre 3 niveles de staking diferentes con cantidades mínimas variables',
    'staking.starter': 'Principiante',
    'staking.standard': 'Estándar',
    'staking.premium': 'Premium',
    'staking.weekly': 'Semanal',
    'staking.minimum': 'Mínimo',
    'staking.lock_time': 'Tiempo de Bloqueo',
    'staking.yearly': 'Anual (aprox.)',
    'staking.pool_capacity': 'Capacidad del Pool',
    'staking.description_250': '250 euros mínimo - 0.5% rendimiento semanal',
    'staking.description_500': '500 euros mínimo - 1% rendimiento semanal',
    'staking.description_1000': '1000 euros mínimo - 2% rendimiento semanal',
    'staking.btn_stake': 'Hacer Staking Ahora',

    // Active Positions
    'positions.title': 'Tus Posiciones Activas',
    'positions.description': 'Monitorea y gestiona tus posiciones de staking en BNB Chain',
    'positions.staked_amount': 'Cantidad en Staking',
    'positions.current_rewards': 'Recompensas Actuales',
    'positions.weeks_active': 'Semanas Activas',
    'positions.status': 'Estado',
    'positions.network': 'Red',
    'positions.unlocked': 'Desbloqueado',
    'positions.locked': 'Bloqueado',
    'positions.btn_rewards': 'Recompensas',
    'positions.btn_unstake': 'Retirar',

    // Staking Modals
    'modal.stake_title': 'Staking BNB Chain',
    'modal.weekly_return': 'Rendimiento Semanal',
    'modal.lock_time': 'Tiempo de Bloqueo',
    'modal.one_week': '1 Semana',
    'modal.token': 'Token',
    'modal.network': 'Red',
    'modal.yearly_approx': 'Anual (aprox.)',
    'modal.amount_label': 'Cantidad en Euros para Staking',
    'modal.amount_placeholder': 'Mínimo: {amount} EUR',
    'modal.balance': 'Balance',
    'modal.minimum_note': 'Mínimo: €{amount} | Semanal: {rate}% | Bloqueo 1 Semana',
    'modal.connect_wallet': 'Por favor conecta tu wallet para BNB Smart Chain',
    'modal.estimated_returns': 'Rendimientos Estimados',
    'modal.weekly': 'Semanal',
    'modal.monthly': 'Mensual (aprox.)',
    'modal.yearly': 'Anual (aprox.)',
    'modal.btn_cancel': 'Cancelar',
    'modal.btn_stake': 'Hacer Staking €{amount}',
    'modal.processing': 'Procesando...',
    'modal.meets_requirements': '✓ La cantidad cumple los requisitos mínimos',

    // Footer
    'footer.description': 'Infraestructura de staking descentralizada de grado industrial diseñada para máxima eficiencia.',
    'footer.protocol': 'Protocolo',
    'footer.community': 'Comunidad',
    'footer.resources': 'Recursos',
    'footer.documentation': 'Documentación',
    'footer.whitepaper': 'Whitepaper',
    'footer.security': 'Seguridad',
    'footer.bug_bounty': 'Bug Bounty',
    'footer.brand_assets': 'Recursos de Marca',
    'footer.discord': 'Discord',
    'footer.telegram': 'Telegram',
    'footer.twitter': 'Twitter',
    'footer.github': 'GitHub',
    'footer.copyright': '© 2024 Stake Fabrik. Todos los derechos reservados.',

    // Governance
    'governance.badge': 'Gobernanza Descentralizada',
    'governance.title1': 'STAKE',
    'governance.title2': 'GOBERNANZA',
    'governance.subtitle': 'DEMOCRACIA INDUSTRIAL',
    'governance.description': 'Da forma al futuro de Stake Fabrik a través de la gobernanza descentralizada. Vota propuestas, delega tus tokens y participa en decisiones de protocolo de nivel industrial.',
    'governance.voting_power': 'Poder de Voto',
    'governance.participation': 'Participación',
    'governance.treasury': 'Tesorería',
    'governance.btn_create': 'Crear Propuesta',
    'governance.btn_delegates': 'Ver Delegados',

    // Analytics
    'analytics.badge': 'Analíticas en Tiempo Real',
    'analytics.title1': 'STAKE',
    'analytics.title2': 'ANALÍTICAS',
    'analytics.subtitle': 'MÉTRICAS INDUSTRIALES',
    'analytics.description': 'Analíticas completas e insights del ecosistema Stake Fabrik. Rastrea rendimiento, métricas de usuario y salud del protocolo con precisión de nivel industrial.',
    'analytics.total_tvl': 'TVL Total',
    'analytics.active_users': 'Usuarios Activos',
    'analytics.avg_weekly': 'Promedio Semanal',

    // User Profile
    'profile.title': 'PERFIL DE USUARIO',
    'profile.subtitle': 'Panel de Operador Industrial',
    'profile.wallet_info': 'Información del Wallet',
    'profile.address': 'Dirección',
    'profile.network': 'Red',
    'profile.status': 'Estado',
    'profile.connected': 'Conectado',
    'profile.available_balance': 'Balance Disponible',
    'profile.ready_staking': 'Listo para staking',
    'profile.btn_deposit_more': 'Depositar Más',
    'profile.btn_view_transactions': 'Ver Transacciones',
    'profile.staking_statistics': 'Estadísticas de Staking',
    'profile.total_staked': 'Total en Staking',
    'profile.total_rewards': 'Recompensas Totales',
    'profile.active_positions': 'Posiciones Activas',
    'profile.avg_weekly_return': 'Rendimiento Semanal Promedio',
    'profile.account_info': 'Información de Cuenta',
    'profile.member_since': 'Miembro Desde',
    'profile.staking_days': 'Días de Staking',
    'profile.portfolio_value': 'Valor Total del Portafolio',
    'profile.operator_level': 'Nivel de Operador',
    'profile.advanced': 'Avanzado',
    'profile.btn_settings': 'Configuración de Cuenta',
    'profile.btn_bscscan': 'Ver en BSCScan',

    // Deposit Modal
    'deposit.title': 'Depósito de Crypto',
    'deposit.description': 'Envía crypto a la dirección de abajo para financiar tu cuenta de staking',
    'deposit.select_crypto': 'Seleccionar Criptomoneda',
    'deposit.min': 'Mín',
    'deposit.deposit_address': 'Dirección de Depósito',
    'deposit.network': 'Red',
    'deposit.qr_code': 'Código QR',
    'deposit.btn_show_qr': 'Mostrar Código QR',
    'deposit.important_instructions': 'Instrucciones Importantes',
    'deposit.instruction_1': 'Solo envía {token} a esta dirección en {network}',
    'deposit.instruction_2': 'Depósito mínimo: {amount} {token}',
    'deposit.instruction_3': 'Los fondos se acreditarán después de 3-6 confirmaciones de red',
    'deposit.instruction_4': 'No envíes desde cuentas de exchange que no soporten contratos inteligentes',
    'deposit.processing_time': 'Tiempo de Procesamiento',
    'deposit.processing_typical': 'Tiempo típico de procesamiento: 5-15 minutos',
    'deposit.processing_update': 'Tu balance se actualizará automáticamente',
    'deposit.processing_notification': 'Recibirás una notificación cuando lleguen los fondos',
    'deposit.btn_copy': 'Copiar Dirección',
    'deposit.btn_bscscan': 'Ver en BSCScan',
    'deposit.recent_deposits': 'Depósitos Recientes',
    'deposit.confirmed': 'Confirmado',
    'deposit.pending': 'Pendiente',
    'deposit.address_copied': '¡Dirección copiada al portapapeles!',

    // Additional translations
    'features.why_title': '¿Por qué Stake Fabrik?',
    'staking.plans_title': 'Planes de Staking BNB Chain',
    'staking.choose_description': 'Elige tu token preferido y el plan correspondiente. Todos los planes ofrecen pagos semanales en BNB Smart Chain.',
    'staking.choose_tiers': 'Elige entre 3 niveles de staking diferentes con cantidades mínimas variables',
    'staking.start_now': 'Hacer Staking Ahora',
    'positions.monitor': 'Monitorea y gestiona tus posiciones de staking en BNB Chain',
    'modal.weekly_return_label': 'Rendimiento Semanal',
    'modal.yearly_approx_label': 'Anual (aprox.)',
    'modal.amount_minimum': 'Mínimo: {amount} EUR',
    'modal.estimated_weekly': 'Semanal:',
    'modal.estimated_monthly': 'Mensual (aprox.):',
    'modal.estimated_yearly': 'Anual (aprox.):',

    // Common
    'common.weeks': 'semanas',
    'common.days': 'días',
    'common.bnb_chain': 'BNB Chain',
    'common.eur': 'EUR',
    'common.close': 'Cerrar',
    'common.copy': 'Copiar',
    'common.loading': 'Cargando...',
  },

  it: {
    // Header & Navigation
    'nav.staking': 'Staking',
    'nav.governance': 'Governance',
    'nav.analytics': 'Analytics',
    'nav.docs': 'Docs',
    'nav.connect': 'Connetti Wallet',
    'nav.deposit': 'Deposita',
    'nav.profile': 'Profilo',

    // Hero Section
    'hero.badge': 'Staking di Nuova Generazione',
    'hero.title1': 'STAKE',
    'hero.title2': 'FABRIK',
    'hero.subtitle': 'STAKING INDUSTRIALE',
    'hero.description': 'Piani di staking intelligenti basati su euro su BNB Smart Chain. Pagamenti settimanali con la nostra infrastruttura di livello industriale.',
    'hero.weekly': 'Settimanale',
    'hero.your_tvl': 'Il Tuo TVL',
    'hero.smart_chain': 'Smart Chain',
    'hero.cta_stake': 'Inizia Staking',
    'hero.cta_analytics': 'Analytics',
    'hero.live_dashboard': 'Dashboard Live',
    'hero.total_staked': 'Totale in Staking',
    'hero.rewards': 'Ricompense',
    'hero.bnb_chain_token': 'Token BNB Chain',

    // Features Section
    'features.title': 'Perché Stake Fabrik?',
    'features.description': 'La nostra infrastruttura industriale fornisce la massima sicurezza, efficienza e redditività per i tuoi investimenti.',
    'features.security.title': 'Sicurezza Industriale',
    'features.security.description': 'Smart contract testati in battaglia con protocolli di sicurezza di grado industriale e wallet multi-sig.',
    'features.automation.title': 'Operazioni Automatizzate',
    'features.automation.description': 'Meccanismi di staking completamente automatizzati con ricompense composte e ottimizzazione intelligente del rendimento.',
    'features.scalable.title': 'Infrastruttura Scalabile',
    'features.scalable.description': 'Linee di produzione multiple per scalabilità istituzionale con periodi di blocco flessibili.',

    // Staking Plans
    'staking.title': 'Piani di Staking BNB Chain',
    'staking.description': 'Scegli il tuo token preferito e il piano corrispondente. Tutti i piani offrono pagamenti settimanali su BNB Smart Chain.',
    'staking.vista_title': 'Vista Finance (VISTA)',
    'staking.mirror_title': '4-Way Mirror Money (4WMM)',
    'staking.geuro_title': 'GEURO (GEURO)',
    'staking.plan_description': 'Scegli tra 3 livelli di staking diversi con importi minimi variabili',
    'staking.starter': 'Principiante',
    'staking.standard': 'Standard',
    'staking.premium': 'Premium',
    'staking.weekly': 'Settimanale',
    'staking.minimum': 'Minimo',
    'staking.lock_time': 'Tempo di Blocco',
    'staking.yearly': 'Annuale (circa)',
    'staking.pool_capacity': 'Capacità Pool',
    'staking.description_250': '250 euro minimo - 0.5% rendimento settimanale',
    'staking.description_500': '500 euro minimo - 1% rendimento settimanale',
    'staking.description_1000': '1000 euro minimo - 2% rendimento settimanale',
    'staking.btn_stake': 'Fai Staking Ora',

    // Active Positions
    'positions.title': 'Le Tue Posizioni Attive',
    'positions.description': 'Monitora e gestisci le tue posizioni di staking su BNB Chain',
    'positions.staked_amount': 'Importo in Staking',
    'positions.current_rewards': 'Ricompense Attuali',
    'positions.weeks_active': 'Settimane Attive',
    'positions.status': 'Stato',
    'positions.network': 'Rete',
    'positions.unlocked': 'Sbloccato',
    'positions.locked': 'Bloccato',
    'positions.btn_rewards': 'Ricompense',
    'positions.btn_unstake': 'Ritira',

    // Staking Modals
    'modal.stake_title': 'Staking BNB Chain',
    'modal.weekly_return': 'Rendimento Settimanale',
    'modal.lock_time': 'Tempo di Blocco',
    'modal.one_week': '1 Settimana',
    'modal.token': 'Token',
    'modal.network': 'Rete',
    'modal.yearly_approx': 'Annuale (circa)',
    'modal.amount_label': 'Importo in Euro per Staking',
    'modal.amount_placeholder': 'Minimo: {amount} EUR',
    'modal.balance': 'Saldo',
    'modal.minimum_note': 'Minimo: €{amount} | Settimanale: {rate}% | Blocco 1 Settimana',
    'modal.connect_wallet': 'Per favore connetti il tuo wallet per BNB Smart Chain',
    'modal.estimated_returns': 'Rendimenti Stimati',
    'modal.weekly': 'Settimanale',
    'modal.monthly': 'Mensile (circa)',
    'modal.yearly': 'Annuale (circa)',
    'modal.btn_cancel': 'Annulla',
    'modal.btn_stake': 'Fai Staking €{amount}',
    'modal.processing': 'Elaborazione...',
    'modal.meets_requirements': '✓ L\'importo soddisfa i requisiti minimi',

    // Footer
    'footer.description': 'Infrastruttura di staking decentralizzata di grado industriale progettata per la massima efficienza.',
    'footer.protocol': 'Protocollo',
    'footer.community': 'Community',
    'footer.resources': 'Risorse',
    'footer.documentation': 'Documentazione',
    'footer.whitepaper': 'Whitepaper',
    'footer.security': 'Sicurezza',
    'footer.bug_bounty': 'Bug Bounty',
    'footer.brand_assets': 'Asset del Brand',
    'footer.discord': 'Discord',
    'footer.telegram': 'Telegram',
    'footer.twitter': 'Twitter',
    'footer.github': 'GitHub',
    'footer.copyright': '© 2024 Stake Fabrik. Tutti i diritti riservati.',

    // Governance
    'governance.badge': 'Governance Decentralizzata',
    'governance.title1': 'STAKE',
    'governance.title2': 'GOVERNANCE',
    'governance.subtitle': 'DEMOCRAZIA INDUSTRIALE',
    'governance.description': 'Plasma il futuro di Stake Fabrik attraverso la governance decentralizzata. Vota le proposte, delega i tuoi token e partecipa alle decisioni del protocollo di livello industriale.',
    'governance.voting_power': 'Potere di Voto',
    'governance.participation': 'Partecipazione',
    'governance.treasury': 'Tesoreria',
    'governance.btn_create': 'Crea Proposta',
    'governance.btn_delegates': 'Visualizza Delegati',

    // Analytics
    'analytics.badge': 'Analytics in Tempo Reale',
    'analytics.title1': 'STAKE',
    'analytics.title2': 'ANALYTICS',
    'analytics.subtitle': 'METRICHE INDUSTRIALI',
    'analytics.description': 'Analytics complete e approfondimenti sull\'ecosistema Stake Fabrik. Traccia performance, metriche utente e salute del protocollo con precisione di livello industriale.',
    'analytics.total_tvl': 'TVL Totale',
    'analytics.active_users': 'Utenti Attivi',
    'analytics.avg_weekly': 'Media Settimanale',

    // User Profile
    'profile.title': 'PROFILO UTENTE',
    'profile.subtitle': 'Dashboard Operatore Industriale',
    'profile.wallet_info': 'Informazioni Wallet',
    'profile.address': 'Indirizzo',
    'profile.network': 'Rete',
    'profile.status': 'Stato',
    'profile.connected': 'Connesso',
    'profile.available_balance': 'Saldo Disponibile',
    'profile.ready_staking': 'Pronto per staking',
    'profile.btn_deposit_more': 'Deposita Altro',
    'profile.btn_view_transactions': 'Visualizza Transazioni',
    'profile.staking_statistics': 'Statistiche Staking',
    'profile.total_staked': 'Totale in Staking',
    'profile.total_rewards': 'Ricompense Totali',
    'profile.active_positions': 'Posizioni Attive',
    'profile.avg_weekly_return': 'Rendimento Settimanale Medio',
    'profile.account_info': 'Informazioni Account',
    'profile.member_since': 'Membro Dal',
    'profile.staking_days': 'Giorni di Staking',
    'profile.portfolio_value': 'Valore Totale Portafoglio',
    'profile.operator_level': 'Livello Operatore',
    'profile.advanced': 'Avanzato',
    'profile.btn_settings': 'Impostazioni Account',
    'profile.btn_bscscan': 'Visualizza su BSCScan',

    // Deposit Modal
    'deposit.title': 'Deposito Crypto',
    'deposit.description': 'Invia crypto all\'indirizzo sottostante per finanziare il tuo account di staking',
    'deposit.select_crypto': 'Seleziona Criptovaluta',
    'deposit.min': 'Min',
    'deposit.deposit_address': 'Indirizzo di Deposito',
    'deposit.network': 'Rete',
    'deposit.qr_code': 'Codice QR',
    'deposit.btn_show_qr': 'Mostra Codice QR',
    'deposit.important_instructions': 'Istruzioni Importanti',
    'deposit.instruction_1': 'Invia solo {token} a questo indirizzo su {network}',
    'deposit.instruction_2': 'Deposito minimo: {amount} {token}',
    'deposit.instruction_3': 'I fondi saranno accreditati dopo 3-6 conferme di rete',
    'deposit.instruction_4': 'Non inviare da account exchange che non supportano smart contract',
    'deposit.processing_time': 'Tempo di Elaborazione',
    'deposit.processing_typical': 'Tempo tipico di elaborazione: 5-15 minuti',
    'deposit.processing_update': 'Il tuo saldo sarà aggiornato automaticamente',
    'deposit.processing_notification': 'Riceverai una notifica quando arrivano i fondi',
    'deposit.btn_copy': 'Copia Indirizzo',
    'deposit.btn_bscscan': 'Visualizza su BSCScan',
    'deposit.recent_deposits': 'Depositi Recenti',
    'deposit.confirmed': 'Confermato',
    'deposit.pending': 'In Attesa',
    'deposit.address_copied': 'Indirizzo copiato negli appunti!',

    // Additional translations
    'features.why_title': 'Perché Stake Fabrik?',
    'staking.plans_title': 'Piani di Staking BNB Chain',
    'staking.choose_description': 'Scegli il tuo token preferito e il piano corrispondente. Tutti i piani offrono pagamenti settimanali su BNB Smart Chain.',
    'staking.choose_tiers': 'Scegli tra 3 livelli di staking diversi con importi minimi variabili',
    'staking.start_now': 'Fai Staking Ora',
    'positions.monitor': 'Monitora e gestisci le tue posizioni di staking su BNB Chain',
    'modal.weekly_return_label': 'Rendimento Settimanale',
    'modal.yearly_approx_label': 'Annuale (circa)',
    'modal.amount_minimum': 'Minimo: {amount} EUR',
    'modal.estimated_weekly': 'Settimanale:',
    'modal.estimated_monthly': 'Mensile (circa):',
    'modal.estimated_yearly': 'Annuale (circa):',

    // Common
    'common.weeks': 'settimane',
    'common.days': 'giorni',
    'common.bnb_chain': 'BNB Chain',
    'common.eur': 'EUR',
    'common.close': 'Chiudi',
    'common.copy': 'Copia',
    'common.loading': 'Caricamento...',
  },

  fr: {
    // Header & Navigation
    'nav.staking': 'Staking',
    'nav.governance': 'Gouvernance',
    'nav.analytics': 'Analytics',
    'nav.docs': 'Docs',
    'nav.connect': 'Connecter Wallet',
    'nav.deposit': 'Dépôt',
    'nav.profile': 'Profil',

    // Hero Section
    'hero.badge': 'Staking Nouvelle Génération',
    'hero.title1': 'STAKE',
    'hero.title2': 'FABRIK',
    'hero.subtitle': 'STAKING INDUSTRIEL',
    'hero.description': 'Plans de staking intelligents basés sur l\'euro sur BNB Smart Chain. Paiements hebdomadaires avec notre infrastructure de niveau industriel.',
    'hero.weekly': 'Hebdomadaire',
    'hero.your_tvl': 'Votre TVL',
    'hero.smart_chain': 'Smart Chain',
    'hero.cta_stake': 'Commencer le Staking',
    'hero.cta_analytics': 'Analytics',
    'hero.live_dashboard': 'Tableau de Bord Live',
    'hero.total_staked': 'Total en Staking',
    'hero.rewards': 'Récompenses',
    'hero.bnb_chain_token': 'Token BNB Chain',

    // Features Section
    'features.title': 'Pourquoi Stake Fabrik?',
    'features.description': 'Notre infrastructure industrielle fournit la sécurité, l\'efficacité et la rentabilité maximales pour vos investissements.',
    'features.security.title': 'Sécurité Industrielle',
    'features.security.description': 'Smart contracts éprouvés avec des protocoles de sécurité de niveau industriel et des wallets multi-sig.',
    'features.automation.title': 'Opérations Automatisées',
    'features.automation.description': 'Mécanismes de staking entièrement automatisés avec récompenses composées et optimisation intelligente du rendement.',
    'features.scalable.title': 'Infrastructure Évolutive',
    'features.scalable.description': 'Lignes de production multiples pour une mise à l\'échelle institutionnelle avec des périodes de verrouillage flexibles.',

    // Staking Plans
    'staking.title': 'Plans de Staking BNB Chain',
    'staking.description': 'Choisissez votre token préféré et le plan correspondant. Tous les plans offrent des paiements hebdomadaires sur BNB Smart Chain.',
    'staking.vista_title': 'Vista Finance (VISTA)',
    'staking.mirror_title': '4-Way Mirror Money (4WMM)',
    'staking.geuro_title': 'GEURO (GEURO)',
    'staking.plan_description': 'Choisissez parmi 3 niveaux de staking différents avec des montants minimums variables',
    'staking.starter': 'Débutant',
    'staking.standard': 'Standard',
    'staking.premium': 'Premium',
    'staking.weekly': 'Hebdomadaire',
    'staking.minimum': 'Minimum',
    'staking.lock_time': 'Temps de Verrouillage',
    'staking.yearly': 'Annuel (environ)',
    'staking.pool_capacity': 'Capacité du Pool',
    'staking.description_250': '250 euros minimum - 0.5% rendement hebdomadaire',
    'staking.description_500': '500 euros minimum - 1% rendement hebdomadaire',
    'staking.description_1000': '1000 euros minimum - 2% rendement hebdomadaire',
    'staking.btn_stake': 'Faire du Staking Maintenant',

    // Active Positions
    'positions.title': 'Vos Positions Actives',
    'positions.description': 'Surveillez et gérez vos positions de staking sur BNB Chain',
    'positions.staked_amount': 'Montant en Staking',
    'positions.current_rewards': 'Récompenses Actuelles',
    'positions.weeks_active': 'Semaines Actives',
    'positions.status': 'Statut',
    'positions.network': 'Réseau',
    'positions.unlocked': 'Déverrouillé',
    'positions.locked': 'Verrouillé',
    'positions.btn_rewards': 'Récompenses',
    'positions.btn_unstake': 'Retirer',

    // Staking Modals
    'modal.stake_title': 'Staking BNB Chain',
    'modal.weekly_return': 'Rendement Hebdomadaire',
    'modal.lock_time': 'Temps de Verrouillage',
    'modal.one_week': '1 Semaine',
    'modal.token': 'Token',
    'modal.network': 'Réseau',
    'modal.yearly_approx': 'Annuel (environ)',
    'modal.amount_label': 'Montant en Euros pour Staking',
    'modal.amount_placeholder': 'Minimum: {amount} EUR',
    'modal.balance': 'Solde',
    'modal.minimum_note': 'Minimum: €{amount} | Hebdomadaire: {rate}% | Verrouillage 1 Semaine',
    'modal.connect_wallet': 'Veuillez connecter votre wallet pour BNB Smart Chain',
    'modal.estimated_returns': 'Rendements Estimés',
    'modal.weekly': 'Hebdomadaire',
    'modal.monthly': 'Mensuel (environ)',
    'modal.yearly': 'Annuel (environ)',
    'modal.btn_cancel': 'Annuler',
    'modal.btn_stake': 'Faire du Staking €{amount}',
    'modal.processing': 'Traitement...',
    'modal.meets_requirements': '✓ Le montant répond aux exigences minimales',

    // Footer
    'footer.description': 'Infrastructure de staking décentralisée de niveau industriel conçue pour une efficacité maximale.',
    'footer.protocol': 'Protocole',
    'footer.community': 'Communauté',
    'footer.resources': 'Ressources',
    'footer.documentation': 'Documentation',
    'footer.whitepaper': 'Whitepaper',
    'footer.security': 'Sécurité',
    'footer.bug_bounty': 'Bug Bounty',
    'footer.brand_assets': 'Assets de Marque',
    'footer.discord': 'Discord',
    'footer.telegram': 'Telegram',
    'footer.twitter': 'Twitter',
    'footer.github': 'GitHub',
    'footer.copyright': '© 2024 Stake Fabrik. Tous droits réservés.',

    // Governance
    'governance.badge': 'Gouvernance Décentralisée',
    'governance.title1': 'STAKE',
    'governance.title2': 'GOUVERNANCE',
    'governance.subtitle': 'DÉMOCRATIE INDUSTRIELLE',
    'governance.description': 'Façonnez l\'avenir de Stake Fabrik grâce à la gouvernance décentralisée. Votez sur les propositions, déléguez vos tokens et participez aux décisions du protocole de niveau industriel.',
    'governance.voting_power': 'Pouvoir de Vote',
    'governance.participation': 'Participation',
    'governance.treasury': 'Trésorerie',
    'governance.btn_create': 'Créer une Proposition',
    'governance.btn_delegates': 'Voir les Délégués',

    // Analytics
    'analytics.badge': 'Analytics en Temps Réel',
    'analytics.title1': 'STAKE',
    'analytics.title2': 'ANALYTICS',
    'analytics.subtitle': 'MÉTRIQUES INDUSTRIELLES',
    'analytics.description': 'Analytics complètes et aperçus de l\'écosystème Stake Fabrik. Suivez les performances, les métriques utilisateur et la santé du protocole avec une précision de niveau industriel.',
    'analytics.total_tvl': 'TVL Total',
    'analytics.active_users': 'Utilisateurs Actifs',
    'analytics.avg_weekly': 'Moyenne Hebdomadaire',

    // User Profile
    'profile.title': 'PROFIL UTILISATEUR',
    'profile.subtitle': 'Tableau de Bord Opérateur Industriel',
    'profile.wallet_info': 'Informations Wallet',
    'profile.address': 'Adresse',
    'profile.network': 'Réseau',
    'profile.status': 'Statut',
    'profile.connected': 'Connecté',
    'profile.available_balance': 'Solde Disponible',
    'profile.ready_staking': 'Prêt pour le staking',
    'profile.btn_deposit_more': 'Déposer Plus',
    'profile.btn_view_transactions': 'Voir les Transactions',
    'profile.staking_statistics': 'Statistiques de Staking',
    'profile.total_staked': 'Total en Staking',
    'profile.total_rewards': 'Récompenses Totales',
    'profile.active_positions': 'Positions Actives',
    'profile.avg_weekly_return': 'Rendement Hebdomadaire Moyen',
    'profile.account_info': 'Informations de Compte',
    'profile.member_since': 'Membre Depuis',
    'profile.staking_days': 'Jours de Staking',
    'profile.portfolio_value': 'Valeur Totale du Portefeuille',
    'profile.operator_level': 'Niveau Opérateur',
    'profile.advanced': 'Avancé',
    'profile.btn_settings': 'Paramètres du Compte',
    'profile.btn_bscscan': 'Voir sur BSCScan',

    // Deposit Modal
    'deposit.title': 'Dépôt Crypto',
    'deposit.description': 'Envoyez de la crypto à l\'adresse ci-dessous pour financer votre compte de staking',
    'deposit.select_crypto': 'Sélectionner Cryptomonnaie',
    'deposit.min': 'Min',
    'deposit.deposit_address': 'Adresse de Dépôt',
    'deposit.network': 'Réseau',
    'deposit.qr_code': 'Code QR',
    'deposit.btn_show_qr': 'Afficher le Code QR',
    'deposit.important_instructions': 'Instructions Importantes',
    'deposit.instruction_1': 'Envoyez uniquement {token} à cette adresse sur {network}',
    'deposit.instruction_2': 'Dépôt minimum: {amount} {token}',
    'deposit.instruction_3': 'Les fonds seront crédités après 3-6 confirmations réseau',
    'deposit.instruction_4': 'N\'envoyez pas depuis des comptes d\'exchange qui ne supportent pas les smart contracts',
    'deposit.processing_time': 'Temps de Traitement',
    'deposit.processing_typical': 'Temps de traitement typique: 5-15 minutes',
    'deposit.processing_update': 'Votre solde sera automatiquement mis à jour',
    'deposit.processing_notification': 'Vous recevrez une notification quand les fonds arrivent',
    'deposit.btn_copy': 'Copier l\'Adresse',
    'deposit.btn_bscscan': 'Voir sur BSCScan',
    'deposit.recent_deposits': 'Dépôts Récents',
    'deposit.confirmed': 'Confirmé',
    'deposit.pending': 'En Attente',
    'deposit.address_copied': 'Adresse copiée dans le presse-papier!',

    // Additional translations
    'features.why_title': 'Pourquoi Stake Fabrik?',
    'staking.plans_title': 'Plans de Staking BNB Chain',
    'staking.choose_description': 'Choisissez votre token préféré et le plan correspondant. Tous les plans offrent des paiements hebdomadaires sur BNB Smart Chain.',
    'staking.choose_tiers': 'Choisissez parmi 3 niveaux de staking différents avec des montants minimums variables',
    'staking.start_now': 'Faire du Staking Maintenant',
    'positions.monitor': 'Surveillez et gérez vos positions de staking sur BNB Chain',
    'modal.weekly_return_label': 'Rendement Hebdomadaire',
    'modal.yearly_approx_label': 'Annuel (environ)',
    'modal.amount_minimum': 'Minimum: {amount} EUR',
    'modal.estimated_weekly': 'Hebdomadaire:',
    'modal.estimated_monthly': 'Mensuel (environ):',
    'modal.estimated_yearly': 'Annuel (environ):',

    // Common
    'common.weeks': 'semaines',
    'common.days': 'jours',
    'common.bnb_chain': 'BNB Chain',
    'common.eur': 'EUR',
    'common.close': 'Fermer',
    'common.copy': 'Copier',
    'common.loading': 'Chargement...',
  }
}
